name: my frist workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: list and read files 
          run: |
             echo "my first git actions"
              ls -ltra
              cat README.md

        - name: generate ASCII artwork
          run:  cowsay -f dragon "run for cover , i am a dragonn raww" >> dragon.txt     

       # - name: list files
       #   run: ls
          
       # - name: read file
       #   run: cat README.md
          
